#ifndef MOTOR_H
#define MOTOR_H

#include "main.h"

#define MOTOR_EN_PIN GPIO_PIN_0
#define MOTOR_EN_PORT GPIOA
#define MOTOR_IN_PIN GPIO_PIN_1
#define MOTOR_IN_PORT GPIOC

#define ALL_MOTOR_START() HAL_GPIO_WritePin(MOTOR_EN_PORT, MOTOR_EN_PIN, GPIO_PIN_SET)
#define ALL_MOTOR_STOP() HAL_GPIO_WritePin(MOTOR_EN_PORT, MOTOR_EN_PIN, GPIO_PIN_RESET)

#define VIBRATEMOTOR_IN_PIN GPIO_PIN_2
#define VIBRATEMOTOR_IN_PORT GPIOC


#endif